[tool.mypy]
python_version = "3.10"
packages = ["UARecords"]
strict = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_optional = true
disallow_any_generics = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = false
ignore_missing_imports = true

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["UARecords"]