register(
    GRAMPLET,
    id="UARecords Gramplet",
    name="Forms for Ukrainian vital records with AI-assisted reconciliation.",
    description="Gramplet interface for UA Records",
    status=STABLE,
    version="1.0.0",
    gramps_target_version="6.0",
    navtypes=["Person"],
    fname="UARecords.py",
    gramplet="UARecords",
    height=375,
    detached_width=510,
    detached_height=480,
    expand=True,
    gramplet_title="🇺🇦 UARecords",
    help_url="UARecords",
    include_in_listing=True,
)
